### ISSUE TITLE
Image Captions

### ISSUE THREAD

**Issue by metastange** [arsmentis/wdet-conversion#79] opened 2021-11-10 21:33 UTC
We are using the credit field in the media metadata for image credit. Need to figure out a solution to adding captions to images in specific posts (not across the entire site).

Example: https://wdet.org/posts/2021/09/10/91406-xiao-dong-weis-livonia-home-is-a-celebration-of-music-and-chinese-culture/

This might be related to #71 ; adding @artlogic in case!

**Comment by artlogic** [comment] 2021-11-11 00:47
@metastange you can use the caption field in WordPress - go ahead and try this out and see how if it works as you'd expect.

**Comment by metastange** [comment] 2021-11-11 13:33
Sorry, I misspoke in my original post - the _caption_ field in the media library is being used for image credit and applies to the media sitewide. We need a solution to include individualized image captions that are specific to the post/content.

**Comment by artlogic** [comment] 2021-11-11 15:13
The caption field will not be used for image credits on the next import.

I believe you are able to edit/create a caption when you add an image to a post. Have you tried this?

**Comment by metastange** [comment] 2021-11-11 15:29
> The caption field will not be used for image credits on the next import.
They'll still be audience-facing though, correct?
> I believe you are able to edit/create a caption when you add an image to a post. Have you tried this?
That was the point of this ticket - @wdet30 was not immediately able to demonstrate how to do this during training. I will look into it further/experiment later.

**Comment by metastange** [comment] 2021-11-11 22:19
Figured this out and will add to training documentation - I still have a question about how credit will be displayed; In the example linked above, the first inline photo has both a credit and a caption. @artlogic, when you import the credits, is this how it will function on the new site as well?

**Comment by artlogic** [comment] 2021-11-11 22:26
That's the plan. I will attempt to set up a demo tonight.

**Comment by metastange** [comment] 2021-11-15 14:05
Checking the status on this issue. Looking for clarity about what field content creators should be adding their photo credit too; we're launching training this week so the sooner I can get that info, the better.

**Comment by artlogic** [comment] 2021-11-15 16:33
Unfortunately I lost access to the VPN over the weekend and haven't been able to do the work needed to complete this. As soon as I regain access, I'll get this going. Hopefully this evening.

**Comment by artlogic** [comment] 2021-11-15 16:34
@metastange one additionally piece of info - it will be a custom field - I will get that part setup now at least.

**Comment by artlogic** [comment] 2021-11-15 16:42
@metastange Please try to edit a media item on wdetcms and you should see the new fields - let me know if anything needs to change - I would try a few different variations on how you normally do credit.

**Comment by metastange** [comment] 2021-11-15 17:43
@artlogic I'm seeing the new fields (and the process is perfect!) but they are not populating on the front-end. I tried inputting images both in-line and as the thumbnail and am not seeing the credit.

**Comment by artlogic** [comment] 2021-11-15 17:45
I can't populate the front end until I regain server access. Hopefully soon
here.

- James

**Comment by metastange** [comment] 2021-11-15 17:45
oh got it; well the backend is perf, thank you!

**Comment by artlogic** [comment] 2021-11-23 07:37
At this point I believe my portion of this is actually a duplicate of #69. Removing my assignment - please re-add if needed.

**Closed** 2021-11-23 13:47 UTC
Labels: import issue
